version: 0.2
            
phases:
  install:
    commands:
      - sudo apt-get update -y
      - sudo apt-get install -y wget
  build:
    commands:
      - zip infrastructure.zip *
  post_build:
    commands:
      - echo No post build yet
      
artifacts:
  type: zip
  files:
    - '**/*'
  discard-paths: no